apiVersion: v1
kind: Service
metadata:
  name: {{ include "tron.fullname" . }}
  labels:
    {{- include "tron.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 8090
      targetPort: http
      protocol: TCP
    - name: listen
      port: 18888
      targetPort: listen
      protocol: TCP
    - name: rpc
      port: 50051
      targetPort: rpc
      protocol: TCP
  selector:
    {{- include "tron.selectorLabels" . | nindent 4 }}
